### PR TITLE
Enforce UTF-8 conversion of strings on insert.

### PR DESCRIPTION
**Pull request by xtrasimplicity**
As per the issue outlined in the Thinking-Sphinx repository, here: https://github.com/pat/thinking-sphinx/issues/262#issuecomment-358532530

Please let me know if you'd like me to make any adjustments.

Thanks!

### CODE REVIEW

**Comment by bibendi** [comment]
IMHO, the Riddle should not care about the encoding. This is an extra overhead for us.

**Comment by xtrasimplicity** [comment]
From what I understand, thinking-sphinx requires strings to be encoded in
UTF-8.

I'm not at my computer at the moment so I'll have to take another look
later, but would you suggest I look at patching TS, instead?

Thanks!

**Comment by pat** [comment]
I'm still pondering _where_ this process should happen, but given Sphinx's documentation says it expects text to be UTF-8, I think a check somewhere along the way is wise.

http://sphinxsearch.com/docs/current.html#charsets

**Comment by pat** [comment]
So… I've pushed [a commit](https://github.com/pat/thinking-sphinx/commit/9ae38f2f7dc97142a09b22eff386c43210b5cb6e) to Thinking Sphinx that should cover this issue off.  That means we don't need this patch in Riddle, though it's still appreciated!

@xtrasimplicity: from your stack-trace in the other issue, it looks like you're using MRI 1.9.x - which I'm not actively supporting. That's much of a muchness, but it's worth noting that MRI 2 has all strings with a UTF-8 encoding by default. Given all of this: I'd expect that even without my patch, upgrading to MRI 2.x for your app will likely solve your problem (and would be wise generally from a security perspective - though I know quite well from my own projects that it can be quite painful to upgrade).

**Pull request closed without merging**
