### PR TITLE
Fix some spec failures

### PR DESCRIPTION
**Pull request by dvandersluis**
Fix spec errors leading to the following failures:
- <code>`expect { }.not_to raise_error(SpecificErrorClass)` is not valid, use `expect { }.not_to raise_error` (with no args) instead</code>
- <code>undefined method `stub!`</code>

### CODE REVIEW

**Comment by pat** [comment]
Are you sure `raise_error(error_class)` helper really been removed? It's still in the Spec documentation: http://rspec.info/documentation/3.2/rspec-expectations/#Expecting_errors

**Comment by dvandersluis** [comment]
I'm not 100% sure, but when I ran the test with `bundle exec rake` (and also with `bundle exec rspec`), it complained, and both of those should be using the versions specified in the gemfile...

**Comment by dvandersluis** [comment]
I think what the confusion is is that a negative expectation (ie. `not_to raise_error`) does not want a class, whereas a positive expecatation (ie. `to raise_error`) can test for a specific class of exception.

**Comment by pat** [comment]
Makes sense. Thanks :)

**Pull request merged**
